name: Update Custom_Clash_Mainland.ini

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: ''
  push:
    paths:
      - cfg/Custom_Clash.ini
  workflow_dispatch:

jobs:
  update-mainland:
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: ${{ inputs.branch != '' && inputs.branch || github.ref_name }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Custom_Clash_Mainland.ini
        run: python py/generate_mainland.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cfg/Custom_Clash_Mainland.ini

          if ! git diff --cached --quiet; then
            git commit -m "Update Custom_Clash_Mainland.ini based on Custom_Clash.ini"
            git pull --rebase origin "${TARGET_BRANCH}"
            git push origin HEAD:"${TARGET_BRANCH}"
          else
            echo "No changes to commit."
